import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { NavBar } from '@/components/NavBar'
import Banner from '@/components/Banner'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <NavBar/>
        <Banner/>
        <Skills/>
        <Projects/>
        <Contact/>
      </main>
    </>
  )
}
